package:
  nginx:
    installed: true
service:
  nginx:
    enabled: true
    running: true
port:
  tcp:80:
    listening: true
  tcp:443:
    listening: true
command:
  nginx -t:
    exit-status: 0
    stderr:
      - 'nginx: the configuration file /etc/nginx/nginx.conf syntax is ok'
      - 'nginx: configuration file /etc/nginx/nginx.conf test is successful'
  curl -s http://localhost/:
    exit-status: 0
    stdout:
      - <head><title>301 Moved Permanently</title></head>
      - <center><h1>301 Moved Permanently</h1></center>
  curl -s -k -v --tlsv1.2 https://localhost/:
    exit-status: 0
    stdout:
      - Hello world
      - I'm Test Page
    stderr:
      - < HTTP/2 200
      - '< server: nginx'
