---
# tasks file for nginx

### 事前タスク
- name: フォルダ回収先の作成
  ansible.builtin.include_tasks:
    file: roles/file_Recovery/tasks/1pre_mkdir.yml
### 事前タスク END

### nginx インストール
- name: nginxインストール
  ansible.builtin.include_tasks:
    file: "include/{{ os_version }}.yml"
  tags: task_install

- name: Index html変更
  ansible.builtin.include_tasks:
    file: include/setup_html.yml
  tags: task_html

### HTTPS設定

- name: Nginx HTTPS 設定
  ansible.builtin.include_tasks:
    file: include/nginx_tls.yml
  tags: task_nginx

- name: HTTPS ファイヤーウォール 設定
  ansible.builtin.include_tasks:
    file: include/firewalld.yml
  tags: task_nginx
  when: ansible_os_family == "RedHat"

###  Nginx設定テスト

- name: nginx Gossる
  ansible.builtin.include_tasks:
    file: include/goss.yml
  tags: task_goss

### 事後タスク
- name: ファイル回収タスク
  ansible.builtin.include_tasks:
    file: roles/file_Recovery/tasks/2post_Recovery.yml
### 事後タスク END
