---
### 監視サーバの構築
- name: leppサーバ設定（Nginx PHP MariaDB）
  hosts: lepp
  become: true
  roles:
    - { role: self_certificate_authority/, tags: role_ca }
    - { role: postgresql, tags: role_db }
    - { role: php_fpm, tags: role_php }
    - { role: nginx, tags: role_web }
    - { role: nginx_php_fpm, tags: role_webphp }
    - { role: adminer, tags: role_adminer }
