services:
  ansible:
    hostname: 'ansible'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    working_dir: '/workspace'
    # ホストと同じUID/GIDで実行
    user: "${UID}:${GID}"
    volumes:
      - .:/workspace
      - ~/.ssh:/home/vscode/.ssh
    tty: true
    stdin_open: true