### システムセキュリティ最新化
- name: システム最新化
  hosts: lepp
  become: true

  pre_tasks:
    - name: アップデート操作拡張変数値
      ansible.builtin.debug:
        msg:
          - 'RedHat系：「-e sec=false」フルアップデート'

  handlers:
    - name: reboot_system
      ansible.builtin.reboot:
        msg: "システムを再起動します。"
      when:
        - ansible_virtualization_type != "docker"
        - ansible_virtualization_type != "container"
        - ansible_env.GITHUB_ACTIONS is not defined or not ansible_env.GITHUB_ACTIONS

  tasks:
    - name: RedHat
      when: ansible_os_family == 'RedHat'
      block:
        - name: "{{ ansible_distribution }}システム最新化(デフォルトセキュリティ項目のみ）"
          ansible.builtin.dnf:
            name: '*'
            state: "{{ sys | default('latest') }}"
            security: "{{ sec | default(true) }}"
          register: update_result
          notify: reboot_system

        - name: RedHat システム更新結果
          ansible.builtin.debug:
            var: update_result.results
