# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |p|
    p.management_network_address = '16.46.96.0/24'
  end

  config.vm.define "lepp" do |machine|
    machine.vm.box = "generic/rocky8"
    machine.vm.hostname = "lepp.example.com"
    machine.vm.network "private_network", ip: "10.116.0.10"
    machine.vm.network "public_network", ip: "192.168.246.113", bridge:'br0', dev: 'br0'
    machine.vm.provider "libvirt" do |spec|
      spec.cpus = 4
      spec.memory = 4096
    end
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision "shell", inline: "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"

end
