--- ### roles/SSH_setup/tasks/include/ssh.yml

### SSHデーモン設定

- name: setup ssh deamon
  when: not ansible_check_mode
  block:
    - name: sshd.conf元ファイルを確認
      ansible.builtin.stat:
        path: "{{ sshd_conf_path }}"
      register: check_file

  #  - debug: var=check_file

    - name: sshd.conf元ファイルをバックアップ
      ansible.builtin.copy:
        src: "{{ item.remote_file }}"
        dest: "{{ linux_remote_backup_dir }}/{{ item.remote_file | basename }}"
        mode: "{{ item.mod }}"
        force: false
        remote_src: true
      with_items: "{{ mv_sshd_conf }}"
      when: check_file.stat.exists
      register: cp_result

  #  - debug: var=cp_result

    - name: sshデーモン設定ファイル転送
      ansible.builtin.template:
        src: "{{ item.local_file }}"
        dest: "{{ item.remote_file }}"
        owner: "{{ item.own }}"
        group: "{{ item.gro }}"
        mode: "{{ item.mod }}"
      with_items: "{{ mv_sshd_conf }}"
      register: cp_result
      notify: ssh_restart

  #  - debug: var=cp_result

### SSHデーモン設定 END


### SSHファイヤーウォール設定ファイル

- name: SSH firewall設定ファイル転送
  ansible.builtin.template:
    src: "{{ item.local_file }}"
    dest: "{{ item.remote_file }}"
    owner: "{{ item.own }}"
    group: "{{ item.gro }}"
    mode: "{{ item.mod }}"
  with_items: "{{ mv_ssh_firewall_conf }}"
  register: cp_result

# - debug: var=cp_result

### SSHファイヤーウォール設定ファイル
