---
# tasks/include/php_fpm_nginx file for php_fpm

### iniファイル設定

- name: php.iniファイルの存在を確認
  ansible.builtin.stat:
    path: "{{ php_ini_path }}"
  register: check_file

- name: PHP php.ini設定
  when: check_file.stat.exists
  block:
    - name: php.ini元ファイルをバックアップ
      ansible.builtin.copy:
        src: "{{ php_ini_path }}"
        dest: "{{ linux_remote_backup_dir }}/{{ php_ini_path | basename }}"
        mode: "u+r"
        force: false
        remote_src: true
      register: cp_result
      when: not ansible_check_mode

    - name: php.iniファイルをNginx対応へ変更
      community.general.ini_file:
        path: "{{ php_ini_path }}"
        section: "{{ item.sec }}"
        option: "{{ item.opt }}"
        value: "{{ item.val }}"
        mode: "+r"
      with_items: "{{ php_ini_list }}"
      register: ini_edit

    - name: PHP-FPMサービス起動
      ansible.builtin.systemd:
        state: restarted
        name: php-fpm
        enabled: true
      register: php_system
      when: ini_edit.changed # noqa: no-handler

- name: /etc/php-fpm.d/www.confファイルの存在を確認
  ansible.builtin.stat:
    path: "{{ php_fpm_conf_path }}"
  register: check_file

- name: PHP php.ini設定
  when: check_file.stat.exists
  block:
    - name: php.ini元ファイルをバックアップ
      ansible.builtin.copy:
        src: "{{ php_fpm_conf_path }}"
        dest: "{{ linux_remote_backup_dir }}/{{ php_fpm_conf_path | basename }}"
        mode: "u+r"
        force: false
        remote_src: true
      register: cp_result
      when: not ansible_check_mode

    - name: php.iniファイル変更
      community.general.ini_file:
        path: "{{ php_fpm_conf_path }}"
        section: "{{ item.sec }}"
        option: "{{ item.opt }}"
        value: "{{ item.val }}"
        mode: "+r"
      with_items: "{{ php_fpm_conf_list }}"
      register: php_edit

    - name: PHP-FPM 設定構文確認
      ansible.builtin.command:
        cmd: "php-fpm -t -y {{ php_fpm_conf_path }}"
      register: cmd_php_fpm
      changed_when: cmd_php_fpm.rc != 0
      when: php_edit.changed # noqa: no-handler

    - name: PHP-FPMサービス起動
      ansible.builtin.systemd:
        state: restarted
        name: php-fpm
        enabled: true
      register: php_system
      when: php_edit.changed # noqa: no-handler

- name: php session ディレクトリの存在を確認
  ansible.builtin.stat:
    path: "{{ php_session_dir }}"
  register: check_file

- name: php session ディレクトリの権限を設定
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: nginx
    mode: "0770"
  with_items: "{{ lib_php_dir_list }}"
  when: not ansible_check_mode and check_file.stat.exists # noqa: no-handler
