service:
  php-fpm:
    enabled: true
    running: true
file:
  /etc/php.ini:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
    contains:
    - "/^cgi.fix_pathinfo = 0/"
  /etc/php-fpm.d/www.conf:
    exists: true
    mode: "0644"
    owner: root
    group: root
    filetype: file
    contains:
    - "/^user = nginx/"
    - "/^group = nginx/"
    - "/^listen.owner = nginx/"
    - "/^listen.group = nginx/"
{% if lib_php_dir_list %}
{% for dir in lib_php_dir_list %}
  {{ dir }}:
    exists: true
    mode: "0770"
    owner: root
    group: nginx
    filetype: directory
{% endfor %}
{% endif %}
port:
  tcp:80:
    listening: true
command:
  sudo php-fpm -t -y /etc/php-fpm.d/www.conf:
    exit-status: 0
    stdout: []
    stderr:
    - 'NOTICE: configuration file /etc/php-fpm.d/www.conf test is successful'
    timeout: 10000
  curl -k -s https://localhost/info.php | grep -i FPM | sed -e 's/<[^>]*>//g':
    exit-status: 0
    stdout:
    - Server API FPM/FastCGI
    - php-fpm active
    - fpm.configno valueno value
    - error_log/var/log/php-fpm/www-error.log/var/log/php-fpm/www-error.log
    stderr: []
    timeout: 10000
  curl -k -s https://localhost/info.php | grep 'PHP Version' | tail -1 | sed -e 's/<[^>]*>//g':
    exit-status: 0
    stdout:
    - PHP Version {{ php_version }}
    stderr: []
    timeout: 10000
