" 改行時前のコマンドの頭を繰り返さない
set paste
" 文字コード指定
set fenc=utf-8
" 入力中のコマンドステータスに表示
set showcmd
" 現在の行を強調表示
set cursorline
" インデントはスマートインデントのOFF
set noautoindent
" 括弧入力時の対応する括弧を表示
set showmatch
" コマンドラインの補完
set wildmode=list:longest

" 検索系
" 検索文字列が小文字の場合は大文字小文字を区別なく検索する
"set ignorecase
" 検索文字列に大文字が含まれている場合は区別して検索する
"set smartcase
" 検索文字列入力時に順次対象文字列にヒットさせる
set incsearch
" 検索時に最後まで行ったら最初に戻る
set wrapscan
" 検索語をハイライト表示
set hlsearch
" ESC連打でハイライト解除
nmap <Esc><Esc> :nohlsearch<CR><Esc>

" swapファイル作成先指定
set directory=~/.vim/stmp

set title
