---
# tasks file for common
- name: set OS varibleds
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ os_version }}.yml"
    - "vars/{{ ansible_os_family }}.yml"

- name: フォルダ回収先の作成
  ansible.builtin.include_tasks: roles/file_Recovery/tasks/1pre_mkdir.yml

- name: "{{ ansible_os_family }}環境設定"
  ansible.builtin.include_tasks: "include/{{ ansible_os_family }}.yml"
  tags: task_distro

- name: root ユーザー環境変数
  ansible.builtin.include_tasks: include/root.yml
  tags: task_user

- name: Admin ユーザー環境変数
  ansible.builtin.include_tasks: include/ansible_admin_user.yml
  tags: task_user

- name: ホスト名の設定
  ansible.builtin.include_tasks: include/hostname.yml
  tags: task_user
  when:
    - ansible_virtualization_type != "docker"
    - ansible_virtualization_type != "container"
    - ansible_env.GITHUB_ACTIONS is not defined or not ansible_env.GITHUB_ACTIONS

- name: ファイル回収
  ansible.builtin.include_tasks: roles/file_Recovery/tasks/2post_Recovery.yml

- name: Prometheus exporter Gossる
  ansible.builtin.include_tasks:
    file: include/goss.yml
  tags: task_goss
