---

- name: DB接続パッケージインストール
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  register: phpdb
  with_items:
    - php-mysqlnd
    - php-pgsql

- name: インストール結果
  ansible.builtin.debug:
    var: phpdb.results

- name: http netowrk db接続許可
  ansible.posix.seboolean:
    name: httpd_can_network_connect_db
    persistent: true
    state: true
