package:
  php-fpm:
    installed: true
  php-common:
    installed: true
  httpd-filesystem:
    installed: true
  nginx-filesystem:
    installed: true
service:
  php-fpm:
    enabled: true
    running: true
file:
  /etc/php.ini:
    exists: true
    contains:
    - "/^error_log = syslog/"
    - "/^date.timezone = Asia/Tokyo/"
command:
  php -v:
    exit-status: 0
    stdout:
    - 'PHP {{ php_version }}'
  php-fpm -v:
    exit-status: 0
    stdout:
    - 'PHP {{ php_version }}'

